CREATE TABLE IF NOT EXISTS registry.policies (
    pid SERIAL PRIMARY KEY,
    policy_name VARCHAR NOT NULL UNIQUE,
    policy_content TEXT NOT NULL, 
    last_updated TIMESTAMP WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP 
);


INSERT INTO registry.policies (policy_name, policy_content)
VALUES 
    ('P&P', 'Your privacy is important to us. We are committed to protecting your personal information. This policy explains how we collect, use, and disclose your information.'),
    ('T&C', 'By using our services, you agree to be bound by the following terms and conditions. Please read them carefully.');



CREATE TYPE IF NOT EXISTS switch.pcstatus AS ENUM
    ('RECEIVED', 'TRANSFORMED', 'TRANSFORM_FAILED', 'SENT_REQUEST_TO_SWITCH', 'SUCCESS_RESPONSE_FROM_SWITCH', 'FAILURE_RESPONSE_FROM_SWITCH', 'SENT_REQUEST_TO_MQTT', 'SUCCESS_RESPONSE_FROM_MQTT', 'FAILURE_RESPONSE_FROM_MQTT', 'RECEIVED_AND_FAILED');


CREATE TABLE IF NOT EXISTS registry.routes (
    rid SERIAL PRIMARY KEY,
    rname VARCHAR NOT NULL,
    notifier VARCHAR,
    isd BOOLEAN NOT NULL DEFAULT false,
    dconfig JSONB,
    security JSONB,
    sconfig JSONB
);



CREATE TABLE IF NOT EXISTS registry.sbroutes (
    sbid SERIAL PRIMARY KEY,
    rid INTEGER NOT NULL,
    did INTEGER NOT NULL,
    CONSTRAINT sbroutes_did_fkey FOREIGN KEY (did)
        REFERENCES registry.devices (did),
    CONSTRAINT sbroutes_rid_fkey FOREIGN KEY (rid)
        REFERENCES registry.routes (rid)
);



INSERT INTO registry.routes (rname, notifier, isd, dconfig, security, sconfig)
VALUES
('SWITCH_MQTT_CWD', 'mqtt', false, 
 '{
  "callStack": [
    "initialize",
    "validate",
    "decrypt",
    "transform",
    "encrypt",
    "sendResponse"
  ],
  "drouter_mqtt": {
    "pub": {
      "url": "/api/v1/device/{device_id}/publish/transaction",
      "replace": "{device_id}"
    },
    "sub": {
      "url": "/api/v1/device/{device_id}/subscribe/transaction",
      "replace": "{device_id}"
    },
    "host": "mqtts://sandbox.dms.mqtt.pocketatm.in:8883",
    "payload": {
      "money": 0,
      "request_id": ""
    },
    "notifier": "mqtt",
    "initialization": {
      "ca_file": "LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tDQpNSUlERlRDQ0FmMmdBd0lCQWdJVWN5T3R2aFcxcUxDQlRTSjVmMElXZzZwSTB6RXdEUVlKS29aSWh2Y05BUUVMDQpCUUF3R2pFWU1CWUdBMVVFQXd3UFUyRnVaR0p2ZUNCTlVWUlVJRU5CTUI0WERUSTBNVEl3TXpBMU1URXdObG9YDQpEVEkxTVRJd016QTFNVEV3Tmxvd0dqRVlNQllHQTFVRUF3d1BVMkZ1WkdKdmVDQk5VVlJVSUVOQk1JSUJJakFODQpCZ2txaGtpRzl3MEJBUUVGQUFPQ0FROEFNSUlCQ2dLQ0FRRUFza0I4bVQ5cG5EMk1QNkJKY0sza0RWc3l4ZncxDQpSRUp5OXVYWU13Q0I0NS9VNi9kSFQyYW02UVBpeVVPM0pSRU5kbGp2c1FCZHZsa01PUmtFQ3ppZElKN3RoTktYDQpxSUloSVJFaXRUNk0vRXJac2xORzVpVXlxV3JTYkhkcHQrdjNNUjllMzNFOHNvQWhYQ1lLWmlmZmZJSVhmcmVPDQpPQXB2QzloNmJGdnRhTkdjUHBKd2NsbkZNRXFwVWxqVThFb0hMWll6NzRycWFLL1ZYa3ZyaEx1dHUrUldGWjR6DQpheTI1V0kydUwrNi90WmdaLzlyTk5HUTlIN2VJZlZDTGpnb25nQS9VSlIwSlQwZ3RSTFRqcHRRazVFY1Jqc3FMDQo2RWFZYkVtUHhsQVJRS3NrRzZ0QnpPUnBUVGdCOElqdTVqME9kb0tGK05id0VLUDRQekkxUXdvUkF3SURBUUFCDQpvMU13VVRBZEJnTlZIUTRFRmdRVStJTHkzeGdEblQ4TEhuZUZWbERlY0pIRm1ja3dId1lEVlIwakJCZ3dGb0FVDQorSUx5M3hnRG5UOExIbmVGVmxEZWNKSEZtY2t3RHdZRFZSMFRBUUgvQkFVd0F3RUIvekFOQmdrcWhraUc5dzBCDQpBUXNGQUFPQ0FRRUFtQ01OdURnYTdtV1lPOHdUNkh1Tzh4VW1UNVIxNTZmczYyWWg2NWUzNUlHQ2IrT29wNUxFDQovcHVRUjJBZDNJdzNXeEdUNWtFdkR1SHMyTzA2c21VS1FoSVBsYUI0TDZ1azhjcnpoRm1DZGZQYlZnREFYUzhwDQpZQmxoVjBodWJiNGVWbHVCdUJ5UGNqbTl6NHRWcnJhbnVZVG5FdW82UDhsV0ZEUGtPZ3BpbEc4YUxkVWNrTkY4DQpMM21jazJySDFITXpGay9Zc3JjUUJaSFJvWW5vQ0h2bnN5MDBibXFROFM0Y1YwRmRPZlZRRUdkaUlhN2pHaEhODQpzaGF1akUvUkxDdUlnQVhWanM1bVQ3RCtPMzlkY3J6eHhJdUZySWp3MGtydFpCMGQrN0tBaC9tRWhMYmQvRmZODQpVZ1ZycE9aNWZmenA2UXE4M1JXdnJueDNncXhsU1dmdzZ3PT0NCi0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0=",
      "broker_key": "LS0tLS1CRUdJTiBQUklWQVRFIEtFWS0tLS0tDQpNSUlFdlFJQkFEQU5CZ2txaGtpRzl3MEJBUUVGQUFTQ0JLY3dnZ1NqQWdFQUFvSUJBUUM3aFJtZVh2c2grakkzDQpwd2toZ2lrME1GenZXU1MxZzhvVE9TbUdJQVU2T09JMXYvRkxrVjBhTXBHcEJGU2tId2lpVDJ4RzhHaG9teFIvDQpxc0ZERmRCRWo0ejVycFA5SEZ0clR4aFpaT3o3N3hJRXlFdDVWd1RFL0t2SmIvN1BsNEdtTFlNbkgxM2N5QW0xDQozMjBtNUUvR2orVjZ2OUpmU2hPbHVZSEc4YkR3VnJaTndsQ3kvV1VuTlBtdU5MZWtpb1hQeGJJcDI2b3o4UzZQDQpmcWQxaEFmbzJLZnVyMkcwZ3FLaUpsNi9Oc3ZzbE9wKzAxVWpUOU5MQ1Z3TkkwMlVHN1BsQWRCWGlGOG1QK2RkDQpaYzFSWTBGQ0Z0UUozQU9BVHBtUjUwZ1JoUTl0MHFIaENtRWNSQmt5bnRIWlMrYzJUNmVVVGlSWkpCZElPZi95DQp5aDlJcnIxVkFnTUJBQUVDZ2dFQU5ML0t4cG1hVkdNQXFGWVZBL2VNNXJEcUc2dzhYdEV0VVg0RmQ4VGZJNU1uDQowdzNrN3loN2c2aVEvL1lIWjBtUmtMTDkxdkMrdGhwVnlGbjgxb1cyMmVwMXNqRFJVV1NlTk5BQm5mZjlrQnNlDQp1dmlxL24yamlsUTNjTWxQNlE2SituaVlDYlBSb0E4bmFDRnJINE1mQzlDanNZVnZSTDNlVEFLa2hwV3JlOWUwDQpjdkdyL2crWTZNNVZjSVRiUjBlTnljY1IwNDF6RUVxdTM5Q0NzRHh6TU5Kc2RRVmxrL2ErZFhUdkhUQkhpU3o0DQpJVDFSWUxmSDBkTWFtUjFwc3k2TXpCNUhoM3RnR1hNd0ZLYlIwT3k1UW1NRWtUYlFHbGovbUdQem1EUUU5UTBSDQpIWXVuNWhWbUVJcFl2WUM2MUVEZ044TWdMbythaHVFU1ExQjBnQmQyZXdLQmdRRDNOckM3UEppcjUvM244K1JUDQpvWm5JNmFRUUV5WjBVZFZteTFWdzNDcksrNFdGNWlybzR6ZUpvb0FpRDhHbVhCcWNoUjIya1FjRStqNS9URC9vDQpDaXIydFRBcGZKQkJxMC8ybUptTWRSYVB5ZDdJRDRvWUJjTVphY1djdnViN2FpZ3VKV2lMc0FlWWh5WnViTVpMDQpZYllhR2FCNmh2WjlSQm1jMEZDNU5JT2ord0tCZ1FEQ0wwY1dwSjZhR0M4MmtlK0Y0cFoyWVVVS3FoUXRURlc5DQpQMWozMHFKbjJrVnVKc3FoZjgreERPQ2tRdUFqSHZwNGI4cTdXYVdwcXhhK3JEMUFEVFFpMzV4amxqTG9qaUdLDQpzWEVhdlVpNTVhT0ZJNXNCZHlDanhzdVJWdUxNakRrUHc2WFFHQmFsaWVVQXM2SkNKWGFydUxlbCtwY1JCWU9HDQpzdTRMdS9NUzd3S0JnQ2RRSlM3QlppNEFTSnA0YUpqOEcrNmRhUis5UytJM21VNHRpN3JVNkdFN09uS2V0Ymd2DQpXZ2VqTmVrMHhFRG1hTHozVmxCUUkrT2d3QXVTWHA5UjdwOHBGUzJqeDNVSi96OWg2Umt6RFpGME10OXh5UzRrDQp6Ry9nS0RMVEVQeHVWMUZ2Vlg3UlVZUHFDaXlKVThkdEZINTJFTlVyWFV0eVp2aFBFR2REZUtPOUFvR0JBSWFWDQptZUdacXNzR0pBTGdWbkFtd1QyKzRNa3BZOTZaWDN0UW9tcndzOXJpcnVoUFBuVjhUZ2haOG9BbVVZNUY5RGJ3DQoxRVBST0Q1RjgvZW5ETFNOOGlxUmJLU2cveHVyRnBnM3J6cG5JamFsY0JYZ3ZaZmdadURiOFU4RU55Q3B0d3EwDQpBUUlmRCtNZmxYWk5DaEpxUUx0M3hPRG1zemo2NTFPK1E3b2lRN0JGQW9HQVBOWTFBTEFkU2ZRTzdMSTREZU1JDQpGanZ1V3Q2dzNXUE9xUy9zNjJPYW5tbjkrOWpPNllQVURVaUN1OEx0N2U0cXRlZ29hL2NMK0VnaEd2NDhWKzV3DQo0KzJ5VTV4dWNJWWE1WkVYbHdHczZQVHhpckxxeDhLZUtudS9QV3BkOUNORjNmbis4RHBONW1IS09jSzAzSERpDQoxamNyZEh2RUFQU0g5UWRPL04zTFFSQT0NCi0tLS0tRU5EIFBSSVZBVEUgS0VZLS0tLS0=",
      "broker_cert": "LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tDQpNSUlDeVRDQ0FiRUNGQUV1VWQ4ZjY4TDBzdThhZ2ljZHNYQVZTQWFRTUEwR0NTcUdTSWIzRFFFQkN3VUFNQm94DQpHREFXQmdOVkJBTU1EMU5oYm1SaWIzZ2dUVkZVVkNCRFFUQWVGdzB5TkRFeU1ETXdOVEV6TVRoYUZ3MHlOVEV5DQpNRE13TlRFek1UaGFNQ2d4SmpBa0JnTlZCQU1NSFhOaGJtUmliM2d1WkcxekxtMXhkSFF1Y0c5amEyVjBZWFJ0DQpMbWx1TUlJQklqQU5CZ2txaGtpRzl3MEJBUUVGQUFPQ0FROEFNSUlCQ2dLQ0FRRUF1NFVabmw3N0lmb3lONmNKDQpJWUlwTkRCYzcxa2t0WVBLRXprcGhpQUZPamppTmIveFM1RmRHaktScVFSVXBCOElvazlzUnZCb2FKc1VmNnJCDQpReFhRUkkrTSthNlQvUnhiYTA4WVdXVHMrKzhTQk1oTGVWY0V4UHlyeVcvK3o1ZUJwaTJESng5ZDNNZ0p0ZDl0DQpKdVJQeG8vbGVyL1NYMG9UcGJtQnh2R3c4RmEyVGNKUXN2MWxKelQ1cmpTM3BJcUZ6OFd5S2R1cU0vRXVqMzZuDQpkWVFINk5pbjdxOWh0SUtpb2laZXZ6Ykw3SlRxZnROVkkwL1RTd2xjRFNOTmxCdXo1UUhRVjRoZkpqL25YV1hODQpVV05CUWhiVUNkd0RnRTZaa2VkSUVZVVBiZEtoNFFwaEhFUVpNcDdSMlV2bk5rK25sRTRrV1NRWFNEbi84c29mDQpTSzY5VlFJREFRQUJNQTBHQ1NxR1NJYjNEUUVCQ3dVQUE0SUJBUUJQeUFEcmRzbVEybTJVTTNiOXA3SElYcUlqDQo2OGc4b2ExYWZLeFpMdTQ2VWprZnpnQnJDK3NZZ01zZldsT0JKK1F6d0FtbzQ3S2hXTjVKYXppQ3A5c1RNdFEvDQplVStDZWp1cU5uSUZKWWM5YXp3Ym1laXlJSUZxMzhLOStsbmtxK2ttVTJCM1RwQnphTkM4cU85TDhMVS81dmFQDQptUXBGMzR5eW56dVFHT29KcGN6dVgzTW4vZXFxVVA5TS9GQkdLOUFoMEZqTGczTDlCZEx2YjRqc1UyRVBKczFjDQp3TDliSlJZbW1pYlpsS0cvVXMyUkNBNVM3TUZwR0EwUXR0Y25QUlJiYzFnUGNEQ1EvYllNUDYwdnJXZ1BEelpiDQoxS2VJQ2RlUUtuVlpMam1Za2hTMnlrTFRYRXBEelc2TTNxTHFWY0F6V1dsRXkwU0FyT3RWaXkxZEZ4YmYNCi0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0="
    },
    "payloadReplace": {
      "money": "body.txnAmt",
      "request_id": "body.reqRefNo"
    }
  }
}', 
 '{"iv": "7dzhcnrb0016hmj3", "key": "k92ldahavl97s428vxri7x89seoy79sm", "algo": "aes-256-gcm", "dtype": "symDecryptor", "etype": "symEncryptor"}',
 '{"callStack": ["insertIntoCache", "decrypt", "transform", "encrypt", "sendResponse"], "switch_drouter": {"failurePayload": {"statMsg": "Failed to Insert", "reqRefNo": "", "statCode": "F"}, "successPayload": {"statMsg": "Successfully Received", "reqRefNo": "", "statCode": "S"}, "payloadReplacer": {"statMsg": "data.msg", "reqRefNo": "data.reqRefNo", "statCode": "data.statCode"}}}');


INSERT INTO registry.sbroutes (rid, did)
VALUES
(1, 20);
